### ISSUE TITLE
Feature request: Shortcuts for convenient language switching

### ISSUE THREAD

**Issue by gwpl** [backmeupplz/voicy#14]
Hi!
Current workflow for switching language if far from optimal, and I switch a lot between languages.

I have feature request to make switching between few most often used languages more comfortable.

Here are some ideas , but this ticket is not limited to them, it's about making it more ergonomic, so here I go:

* `/l en` - to switch to english
* '/l`
* when I press `[/]` icon , to get not only `/help` but also `/language`
* to make `/language` (and `/l`) to display on a top as first positions "top 5 most used languages" and later alphabetic list of all the rest.
* feature of auto detection (maybe based on most used languages) which language it was and display to user buttons if it was bad selection to manually select other guesses.
* more voicy bots! One per language! So I have `@voicyenbot` `@voicydebot` `@voicyplbot` dedicated for languages and no need to switch ! :)

Just few ideas that come to my mind. I would love to see it more ergonomic to switch between languages. Thank you!

**Comment by backmeupplz** [comment]
Thanks for the suggestion. I don't have much time recently, but I'll try to implement some of the features.

> /l en - to switch to english

Doable

> /l

Doable

> when I press [/] icon , to get not only /help but also /language

Will swamp the commands suggestions window, so won't add it :) /help is sufficient for now

> feature of auto detection (maybe based on most used languages) which language it was and display to user buttons if it was bad selection to manually select other guesses.

I don't think I'll implement it, sorry.

> more voicy bots! One per language! So I have @voicyenbot @voicydebot @voicyplbot dedicated for languages and no need to switch ! :)

Same here, don't think a lot of users will benefit from it

**Comment by gwpl** [comment]
Thank you for your reply,

As I stated before it's more like brainstorming ideas, implementation of
any will be very nice, thank you!

Grzegorz Wierzowiecki
sorry for brevity & typos - typing from phone

**Comment by backmeupplz** [comment]
@gwpl I've implemented `/l` and `/l en`, `/l ru', etc. commands ;) enjoy

**Comment by gwpl** [comment]
Thank you!

Grzegorz Wierzowiecki
sorry for brevity & typos - typing from phone
