### ISSUE TITLE
Есть ли возможность урезать потребление памяти?

### ISSUE THREAD

**Issue by okopok** [backmeupplz/voicy#15]
На бесплатном heroku инстансе падает по лимиту памяти в 512Mb почти сразу, после развёртывания приложения.

З.Ы. Спрашиваю как php'шник ))

**Comment by backmeupplz** [comment]
УУуууууу php ужс. Фуфуфу :))

**Comment by backmeupplz** [comment]
Черт его знает, можно ли урезать, на самом деле — тут ffmpeg достаточно много ест, да и нода тяжеленькая.

**Comment by backmeupplz** [comment]
О, можно монгу отдельно вынести

**Comment by okopok** [comment]
Не уверен, что до ffmpeg вообще доходит, потому, что бот по памяти валится почти сразу, ещё до того, как ему что-то прислать.

**Comment by okopok** [comment]
и в смысле отдельно вынести? Она и так отдельно же )

**Comment by backmeupplz** [comment]
Ну, можно тогда попробовать ограничить память у самого процесса ноды при запуске :) но не уверен, что я могу с этим помочь.
