### ISSUE TITLE
Add opus audio format

### ISSUE THREAD

**Issue by korskantevin** [backmeupplz/voicy#26]
This should be very useful for sharing voice messages from whatsapp

**Comment by backmeupplz** [comment]
Turn on /files :)

**Comment by korskantevin** [comment]
да только бот пишет на файлы opus: У меня не получилось это распознать

**Comment by backmeupplz** [comment]
@korskantevin значит, бот просто не смог распознать этот файл :) бывает, машины еще не идеальны

**Comment by korskantevin** [comment]
могу прислать несколько файлов :) дело же не в одном случае

**Comment by backmeupplz** [comment]
@korskantevin значит, не смог распознать несколько файлов, бывает :)
