### ISSUE TITLE
How can I debug my own copy of voicy?

### ISSUE THREAD

**Issue by rschaerer** [backmeupplz/voicy#3]
Dear all

I've set up my own copy of voicy but all I get as response to a voice message is `👮 I couldn't recognize that`.

:question: How can I debug my installation and configuration?

Wit.ai logs doesn't show any requests, so I think it has something to do with the installation or the wit.ai keymap.

**Comment by backmeupplz** [comment]
Yep, probably it fails before sending the audio to wit.ai. Maybe console.logging along the way? Maybe ffmpeg is failing? Maybe you can breakpoint the code?

**Comment by Aleyasen** [comment]
@backmeupplz I had the same issue related to FFmpeg installation. I think it's better to add FFmpge as one of the requirements in the documentation.
