### ISSUE TITLE
Bot is offline

### ISSUE THREAD

**Issue by Adem1987** [backmeupplz/voicy#4]
Bot does not work anymore.

**Comment by backmeupplz** [comment]
It is under maintenance for the next couple of days.

**Comment by maksimsch** [comment]
when couple of days gonna pass ?

**Comment by Adem1987** [comment]
What do you mean?

**Comment by backmeupplz** [comment]
Probably going to finish it up today :)

**Comment by backmeupplz** [comment]
Finished working, deploying :) Yay!

**Comment by backmeupplz** [comment]
@maksimsch fixed it, thanks for noticing :)
