### ISSUE TITLE
send message when text is ready for better integration with watch and bands

### ISSUE THREAD

**Issue by AoNoAsgard** [backmeupplz/voicy#54]
hi. i want to suggest a config feature.

Something like a config for chat where you can set if the message will be send normally or the moment when the trascription is ready.

for example normally the message is something like "voice recognition has started" and then replaced with the actual text, 
the problem i have with this is that when the notification arrives on the watch or band i can read only the placeholder since it can't read the canged notification.

what i was thinking is more something like the message will be send the moment it finished the transcription.

Thanks if this idea will be taken in consideration.

**Comment by backmeupplz** [comment]
Try /silent
