### ISSUE TITLE
Remove 'putin and his cronies...' text from captions

### ISSUE THREAD

**Issue by lyricalsoul** [backmeupplz/voicy#84]
Expressing yourself against the violence committed by the Russian Federation is a very noble thing to do, specially in a platform full of Putin supporters such as Telegram.

However, adding "Putin and his cronies kill civilians in the war in Ukraine #stopputin" to the end of messages is very confusing and unprofessional. It gives the impression that the audio says that, when in fact it does not. One may say it is literally "shoving words onto your mouth", I guess.

Telegram offers a variety of places for the developer to express their opinions, such as the "About the bot" section, descriptions, `/start` command, etc. It may not have as much of an impact as adding links to the messages, but it would get the message sent across the platform without having to affect the main functionality of the bot, which is to caption audio messages. Politics should not affect applications, specially those who are important to accessibility (such as Voicy). It's simply unfair.

**Comment by backmeupplz** [comment]
I'll surely remove the message right after the war ends and people stop getting killed by Putin and his corrupt government

**Comment by lyricalsoul** [comment]
> Lol. If you think that politics should not affect something, think again.

Do you think it's fair or effective to affect a bot that captions audio messages? Do you think that's going to upset Putin and, just like that, make him stop the war?

Everyone knows about the situation in Ukraine. We are on the internet, after all. Open up Twitter and you'll read about russian missiles being launched upon Ukraine. Everyone who hasn't positioned by now is obviously on Russia's side, so there's no point on appending links to messages.

It's not a politics bot, it's an accessibility tool. Politics shouldn't be involved in it. It should simply do its job and that's it.

**Comment by backmeupplz** [comment]
> Do you think it's fair or effective

Yes, it's more fair and effective than doing nothing.

> Politics shouldn't be involved in it

Lol, politics is involved in everything humans do, like it or not.
