### ISSUE TITLE
Voice recognition works for personal chat but not in groups

### ISSUE THREAD

**Issue by timaschew** [backmeupplz/voicy#88]
I've provided `German` and `English` in the `WIT_LANGUAGES` env variable.
When I start a chat with the bot directly, the voice recognition works fine.

If I invite my bot into a (my) group, voicy prints a message, let me choose the language. I choose it, the engine and voice language but the voice recognition does not work. No response from the bot, nothing in the logs, even when I set to `ENVIRONMENT=development`

**Comment by backmeupplz** [comment]
Try setting up Voicy in the group as well :) or try other voice recognition engines in /engine

**Comment by timaschew** [comment]
> Try setting up Voicy in the group as well :)

How exactly?

I've tried it. The enginie doesn't matter, I've tried all of them.
My voicy but seems to be not triggered by a voice message at all. Only by commands like `/engine`, etc.

**Comment by backmeupplz** [comment]
@timaschew just like you set it up in private messages :) try also turning off /silent and turning on /files

**Comment by timaschew** [comment]
I did same for private chat and for group chat. I've also tried to enable and disable /silent and /files. I've even createed another group, but nothing helps.

Can you please point me to the source code where the bot listen for a voice message?

Maybe the bot needs some special configuration via BotFather?

**Comment by timaschew** [comment]
I found the code `bot.on([':voice', ':video_note'], handleAudio)` I've added some `console.log` lines to the handler. In a group chat the handler is NOT called if I do a voice message.

**Comment by timaschew** [comment]
Found the issue, /setprivacy needs to be disabled.
