### ISSUE TITLE
Worker started, but bot not answering

### ISSUE THREAD

**Issue by CarlosLopezES** [backmeupplz/voicy#89]
Hi,

First of all, thanks for your work. I'm trying to self hosting it, so I clone the repo, created .env, launch yarn to download packages and then launch yarn start as you say in the docs gives me an error.

I explore the package json so I ended launching yarn develop to generate folders, the dist folder is generated and the app.js is launched. It says "Worker XXX started" but the bot dosn't answer to any messages, neither start nor help.

I've tried to add custom console.log on app.js, and I saw that code dosn't reach function runApp() {}, stops before.

I'm on CentOS 7 environment.

Any ideas? Thanks a lot.

**Comment by backmeupplz** [comment]
try removing cluster api, maybe it's not working properly on your machine

**Comment by BigPelmeshka** [comment]
Hi, thank you for your work

Trying to self-host it on WinServer, cannot run neither "yarn start" (command not found), nor "yarn run" (no binary scripts available). 
any ideas?

**Comment by backmeupplz** [comment]
@BigPelmeshka install [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) :)

**Comment by Eyjafja** [comment]
Hi, I'm facing the same issue, did you manage to fix it? If so, how?

**Comment by CarlosLopezES** [comment]
I opted for a Docker fork: https://github.com/EntrixIII/voicy-docker

King regards,

**Comment by lmerega** [comment]
Hi all, I cannot understand what is wrong.
yarn distribute gives me back:

yarn run v1.22.19
$ node dist/app.js
Worker 7844 started
Done in 11.14s.

Please... ideas?

The docker version works flawlessly

TIA

**Comment by lmerega** [comment]
Ok, I solved by changing:
if (Cluster.isPrimary) {
  void runApp()
}
to

void runApp()
