### ISSUE TITLE
Yarn Start not found

### ISSUE THREAD

**Issue by lmerega** [backmeupplz/voicy#91]
Hallo, I am trying to run this wonderful bot on my srever.
I installed everything, but "yarn start" seems to be missing.
I tried "yarn distribute" and this hasppens:

yarn run v1.22.19
$ node dist/app.js
Worker 47722 started
Done in 11.07s.

Can you help me?

TIA

**Comment by backmeupplz** [comment]
try `yarn develop` or `yarn distribute`
